### PR TITLE
Handle response changes for bulk getters in v7.3

### PR DESCRIPTION
**Pull request by mpspahr**
TestRail 7.3 introduced API response changes for the following
bulk getter functions.

getProjects / get_projects
https://support.gurock.com/hc/en-us/articles/7077792415124-Projects#getprojects

getSections / get_sections
https://support.gurock.com/hc/en-us/articles/7077918603412-Sections#getsections

getCases / get_cases
https://support.gurock.com/hc/en-us/articles/7077292642580-Cases#getcases

getMilestones / get_milestones
https://support.gurock.com/hc/en-us/articles/7077723976084-Milestones#getmilestones

getTests / get_tests
https://support.gurock.com/hc/en-us/articles/7077990441108-Tests#gettests

The responses now include offset, limit, size, and links for pagination
traversal.

### CODE REVIEW

**Comment by teodesian** [comment]
Thanks for the contribution Matt.  Would you like to take over maintainership?

**Comment by teodesian** [comment]
tests appear broken, may be a bit before I can get a release out the door

**Comment by teodesian** [comment]
Tests are broken because response formats have radically changed, and the mocks can't deal with it.  It's gonna require a re-generation of the mocks, and there are a few simple mistakes here that are also bad that result in explosions and unhandled stuff when you get an undef response.

It's been years since I've had to regenerate the mocks.  These should all be re-done to not simulate HTTP requests.
I think the only option I have at this point is git rm much of the testsuite, after fixing the obvious bugs.

**Comment by mpspahr** [comment]
Thanks. I see now. I should have a PR submitted later today or early tomorrow.

**Comment by teodesian** [comment]
RE maintainership: as long as you have a PAUSE account (pause.cpan.org) I can transfer maint to you.   It's fairly straightforward on the github end of things.

send me an email george at troglodyne.net and we can work out the details for a handoff

**Comment by teodesian** [comment]
0.052 uploaded to CPAN

**Pull request merged**
